[package]
name = "codemotion-workshop-rust-for-nodejs-developer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "06-iter"
test = false
bench = false